---

- name: 'LampStack - Installation'
  yum:
    name:
      - httpd
      - php
      - php-mysql
      - mariadb-server
      - MySQL-python
    state: present
      
- name: 'LampStack - Restarting/Enabling'
  service:
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
    - mariadb
    - httpd
      
- name: 'LampStack - Creating Virtualhost'
  template:
    src: virtualhost.j2
    dest: /etc/httpd/conf.d/{{domain}}.conf
      
- name: 'LampStack - Creating Documentroot'
  file:
    path: /var/www/html/{{domain}}
    state: directory  
      
      
- name: 'LampStack - Creating info.html'
  copy:
    src: info.html
    dest: /var/www/html/{{domain}}/info.html      
      
- name: 'LampStack - Creating info.php'
  copy:
    src: info.php
    dest: /var/www/html/{{domain}}/info.php
